audit_header: false
title: All About Real Estate with Vickie Landis Rentsel
description: Our mission at Vickie Landis Rentsel Team is to be your best resource for Quakertown real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The Vickie Landis Rentsel Team, your professional Quakertown Real Estate Agents.
show_custom_links: true
custom_links:
  - title: App 
    url: http://app.kw.com/KW17PKOIB
show_custom_links_new_tab: false
custom_links_new_tab:
  - title:
    url:

client:
  name: Vickie Landis Rentsel
  title: Broker/Realtor
  license_number:
  about_markdown: |
    With over 25 years of real estate experience, Vickie Landis has developed a team of the region's best real estate professionals in order to provide you with the greatest real estate service. Focusing on long term planning, Vickie and her team bring the wisdom of conservative wealth building back to real estate.

    When you work with THE VICKIE LANDIS RENTSEL TEAM you are getting the combined expertise, energy, and ingenuity of a team of the area's premier Realtors. With 25 years of real estate experience, Vickie has developed proven systems and strategies that simplify the complicated maze of buying and selling real estate.

    Specializing in Residential, Commercial and Investment Real Estate, Vickie and her team are committed to empowering each client to make wise informed investment decisions when buying and selling real estate. So, whether you're considering buying your first home or liquidating your real estate investment portfolio... begin with a Consultant. THE VICKIE LANDIS RENTSEL TEAM - Making every move count!
  brand: Keller Williams Realty Group
  market: Quakertown
  address: 431 S. West End Blvd Quakertown, PA  18951
  phone: 267-733-0777
  phone_type:
  phone2:
  phone2_type:
  email: LandisRentselTeam@gmail.com
  url: http://nextkeymove.com

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: /homevalue/
  second_CTA_text: Home Search
  second_CTA_URL: https://nextkeymove.kw.com/search
  
sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "What’s Your Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: /homevalue/

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/002.jpg
    CTA_title2: "Looking for a Home?"
    CTA_text2: "Search the entire MLS for your home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: https://nextkeymove.kw.com/search

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: /img/lender-headshot.jpg
  logo_path: /img/lender-logo.png
  name:
  license_number:
  company:
  company_license_number:
  phone:
  email:
  url:

socials:
  review_sm_icons: true
  facebook_url: https://www.facebook.com/VickieLandisRentselTeam/
  linkedin_url: https://www.linkedin.com/in/nextkeymove/
  youtube_url: https://www.youtube.com/channel/UC28PSBcrLNybAjMMXsXcbbA/featured?disable_polymer=1
  twitter_url: https://www.twitter.com/NextKeyMove
  instagram_url:
  pinterest_url:
  zillow_url: https://www.zillow.com/profile/Vickie-Landis-Team/
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: 'Quakertown Real Estate Podcast with Vickie Landis Rentsel'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the Quakertown Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from Vickie Landis Rentsel Team - your professional Quakertown Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in Quakertown, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Vickie Landis Rentsel'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 60
  hero_text: All About Real Estate
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
  post_cta_image: /img/home-value.jpg
  post_cta_image2: /img/home-search.jpg

site_colors:
  brand_color: '#b40101'
  theme_color: '#999999'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: black

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#b40101'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
